-- Dim table PK
CREATE SEQUENCE SEQ_PASSENGER_SK  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Fact table PKs
CREATE SEQUENCE SEQ_FACT_FLIGHT   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FACT_RES      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FACT_LOYALTY  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FACT_INTERACT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FACT_PROMO    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FACT_UPGRADE  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FACT_STAY     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE DIM_DATE (
    DATE_KEY             NUMBER(8)    NOT NULL,  
    FULL_DATE            DATE         NOT NULL,
    DAY_OF_WEEK          VARCHAR2(10) NOT NULL,  
    DAY_NUMBER_IN_WEEK   NUMBER(1)    NOT NULL, 
    DAY_NUMBER_IN_MONTH  NUMBER(2)    NOT NULL,
    DAY_NUMBER_IN_YEAR   NUMBER(3)    NOT NULL,
    WEEK_NUMBER_IN_YEAR  NUMBER(2)    NOT NULL,
    MONTH_NUMBER         NUMBER(2)    NOT NULL,
    MONTH_NAME           VARCHAR2(10) NOT NULL,
    MONTH_SHORT_NAME     VARCHAR2(3)  NOT NULL,
    QUARTER              NUMBER(1)    NOT NULL,
    QUARTER_NAME         VARCHAR2(6)  NOT NULL,  
    YEAR                 NUMBER(4)    NOT NULL,
    IS_WEEKEND           VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    IS_HOLIDAY           VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    SEASON               VARCHAR2(10) NULL,       
    CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY)
);

-- DIM_AIRPORT (role-playing dim).
CREATE TABLE DIM_AIRPORT (
    AIRPORT_ID      NUMBER          NOT NULL,
    IATA_CODE       VARCHAR2(3)     NOT NULL,
    AIRPORT_NAME    VARCHAR2(120)   NOT NULL,
    CITY            VARCHAR2(80)    NOT NULL,
    COUNTRY         VARCHAR2(80)    NOT NULL,
    TIMEZONE        VARCHAR2(80)    NULL,
    TERMINAL_COUNT  NUMBER          NULL,
    CONSTRAINT PK_DIM_AIRPORT PRIMARY KEY (AIRPORT_ID)
);

CREATE TABLE DIM_AIRCRAFT (
    AIRCRAFT_ID          NUMBER        NOT NULL,
    TAIL_NUMBER          VARCHAR2(20)  NOT NULL,
    MODEL                VARCHAR2(80)  NOT NULL,
    MANUFACTURER         VARCHAR2(80)  NOT NULL,
    CAPACITY_ECONOMY     NUMBER        NULL,
    CAPACITY_BUSINESS    NUMBER        NULL,
    CAPACITY_FIRST       NUMBER        NULL,
    TOTAL_CAPACITY       NUMBER        NULL,  -- derived: sum of all cabins
    YEAR_MANUFACTURED    NUMBER(4)     NULL,
    STATUS               VARCHAR2(30)  NOT NULL,
    CONSTRAINT PK_DIM_AIRCRAFT PRIMARY KEY (AIRCRAFT_ID)
);


CREATE TABLE DIM_ROUTE (
    ROUTE_ID                NUMBER         NOT NULL,
    ORIGIN_AIRPORT_ID       NUMBER         NOT NULL,  
    DESTINATION_AIRPORT_ID  NUMBER         NOT NULL,  
    DISTANCE_KM             NUMBER         NULL,
    FLIGHT_DURATION_MIN     NUMBER         NULL,
    IS_INTERNATIONAL        VARCHAR2(1)    DEFAULT 'N' NOT NULL,
    BASE_PRICE_USD          NUMBER(10,2)   NULL,
    CONSTRAINT PK_DIM_ROUTE PRIMARY KEY (ROUTE_ID),
    CONSTRAINT FK_ROUTE_ORIG FOREIGN KEY (ORIGIN_AIRPORT_ID)
        REFERENCES DIM_AIRPORT(AIRPORT_ID),
    CONSTRAINT FK_ROUTE_DEST FOREIGN KEY (DESTINATION_AIRPORT_ID)
        REFERENCES DIM_AIRPORT(AIRPORT_ID)
);

CREATE TABLE DIM_FARE_CLASS (
    FARE_CLASS_ID     NUMBER         NOT NULL,
    FARE_CODE         VARCHAR2(5)    NOT NULL,
    FARE_DESCRIPTION  VARCHAR2(80)   NULL,
    CABIN             VARCHAR2(30)   NOT NULL,
    REFUNDABLE        VARCHAR2(1)    DEFAULT 'N' NOT NULL,
    MILES_MULTIPLIER  NUMBER(5,2)    NULL,
    CONSTRAINT PK_DIM_FARE_CLASS PRIMARY KEY (FARE_CLASS_ID)
);

CREATE TABLE DIM_BOOKING_CHANNEL (
    CHANNEL_ID    NUMBER         NOT NULL,
    CHANNEL_NAME  VARCHAR2(50)   NOT NULL,
    CHANNEL_TYPE  VARCHAR2(50)   NOT NULL,
    IS_ONLINE     VARCHAR2(1)    DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_DIM_BOOKING_CHANNEL PRIMARY KEY (CHANNEL_ID)
);

CREATE TABLE DIM_FF_TIER (
    TIER_ID           NUMBER          NOT NULL,
    TIER_NAME         VARCHAR2(30)    NOT NULL,
    MIN_MILES         NUMBER          NULL,
    LOUNGE_ACCESS     VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    PRIORITY_BOARDING VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    UPGRADE_ELIGIBLE  VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    BONUS_MILES_PCT   NUMBER(5,2)     NULL,
    CONSTRAINT PK_DIM_FF_TIER PRIMARY KEY (TIER_ID)
);

CREATE TABLE DIM_PROMOTION (
    PROMO_ID      NUMBER          NOT NULL,
    PROMO_CODE    VARCHAR2(20)    NOT NULL,
    PROMO_NAME    VARCHAR2(100)   NOT NULL,
    DISCOUNT_PCT  NUMBER(10,2)    NULL,
    MILES_BONUS   VARCHAR2(50)    NULL,
    START_DATE    DATE            NULL,
    END_DATE      DATE            NULL,
    ROUTE_ID      NUMBER          NULL,  -- which route this promo targets
    IS_ACTIVE     VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_DIM_PROMOTION PRIMARY KEY (PROMO_ID),
CONSTRAINT FK_PROMO_ROUTE FOREIGN KEY (ROUTE_ID) REFERENCES DIM_ROUTE(ROUTE_ID)
);

-- multiple physical rows for the same logical passenger.
-- Natural key PASSENGER_ID repeats across versions; SK uniquely
CREATE TABLE DIM_PASSENGER (
    PASSENGER_SK     NUMBER          NOT NULL,  
    PASSENGER_ID     NUMBER          NOT NULL,  
    FIRST_NAME       VARCHAR2(50)    NOT NULL,
    LAST_NAME        VARCHAR2(50)    NOT NULL,
    GENDER           VARCHAR2(1)     NULL,
    DATE_OF_BIRTH    DATE            NULL,
    NATIONALITY      VARCHAR2(50)    NULL,
    PASSPORT_NUMBER  VARCHAR2(30)    NULL,
    EMAIL            VARCHAR2(120)   NULL,
    PHONE            VARCHAR2(40)    NULL,
    FF_NUMBER        VARCHAR2(20)    NULL,
    TIER_ID          NUMBER          NULL,
    TIER_NAME        VARCHAR2(30)    NULL,   
    TOTAL_MILES      NUMBER          DEFAULT 0 NULL,
    JOIN_DATE        DATE            NULL,
    -- SCD2 tracking columns
    EFF_START_DATE   DATE            NOT NULL,
    EFF_END_DATE     DATE            NULL,   -- NULL = this is the current row
    IS_CURRENT       VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    ROW_HASH         VARCHAR2(64)    NULL,   -- hash of tracked columns for change detection
    ETL_INSERT_DATE  DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_DIM_PASSENGER PRIMARY KEY (PASSENGER_SK),
    CONSTRAINT FK_PASS_TIER FOREIGN KEY (TIER_ID) REFERENCES DIM_FF_TIER(TIER_ID)
);

CREATE OR REPLACE TRIGGER TRG_DIM_PASSENGER_SK
BEFORE INSERT ON DIM_PASSENGER
FOR EACH ROW
BEGIN
    IF :NEW.PASSENGER_SK IS NULL THEN
        SELECT SEQ_PASSENGER_SK.NEXTVAL INTO :NEW.PASSENGER_SK FROM DUAL;
    END IF;
END;
/

-- Grain: one row per flight operation.
-- Business process: flight activity and profitability.
-- DIM_AIRPORT is used twice (role-playing): origin and destination.
CREATE TABLE FACT_FLIGHT_ACTIVITY (
    FACT_FLIGHT_ID           NUMBER          NOT NULL,
    -- Degenerate dimensions
    FLIGHT_ID                NUMBER          NOT NULL,
    FLIGHT_NUMBER            VARCHAR2(10)    NOT NULL,
    FLIGHT_STATUS            VARCHAR2(30)    NULL,
    -- FK to dimensions
    DATE_KEY                 NUMBER(8)       NOT NULL,  
    ROUTE_ID                 NUMBER          NOT NULL,  
    AIRCRAFT_ID              NUMBER          NOT NULL,   
    -- ORIGIN_AIRPORT_ID        NUMBER          NOT NULL,   -- FK DIM_AIRPORT (role: origin)
    -- DESTINATION_AIRPORT_ID   NUMBER          NOT NULL,   -- FK DIM_AIRPORT (role: destination)
    
    -- Timestamps kept for audit
    SCHEDULED_DEPARTURE      TIMESTAMP       NULL,
    ACTUAL_DEPARTURE         TIMESTAMP       NULL,
    SCHEDULED_ARRIVAL        TIMESTAMP       NULL,
    ACTUAL_ARRIVAL           TIMESTAMP       NULL,
    -- Operational measures
    DEPARTURE_DELAY_MIN      NUMBER          NULL,   -- actual - scheduled departure
    ARRIVAL_DELAY_MIN        NUMBER          NULL,   -- actual - scheduled arrival
    ACTUAL_DURATION_MIN      NUMBER          NULL,   -- actual arrival - actual departure
    ECONOMY_SEATS_AVAILABLE  NUMBER          NULL,
    BUSINESS_SEATS_AVAILABLE NUMBER          NULL,
    FIRST_SEATS_AVAILABLE    NUMBER          NULL,
    TOTAL_SEATS_AVAILABLE    NUMBER          NULL,
    -- Cost measures (from FLIGHT_COSTS)
    FUEL_COST_USD            NUMBER(10,2)    NULL,
    CREW_COST_USD            NUMBER(10,2)    NULL,
    AIRPORT_FEES_USD         NUMBER(10,2)    NULL,
    MAINTENANCE_COST_USD     NUMBER(10,2)    NULL,
    CATERING_COST_USD        NUMBER(10,2)    NULL,
    TOTAL_COST_USD           NUMBER(10,2)    NULL,
    COST_SOURCE              VARCHAR2(40)    NULL,
    -- ETL metadata
    ETL_LOAD_DATE            DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_FACT_FLIGHT PRIMARY KEY (FACT_FLIGHT_ID),
    CONSTRAINT FK_FFA_DATE  FOREIGN KEY (DATE_KEY)               REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_FFA_ROUTE FOREIGN KEY (ROUTE_ID)               REFERENCES DIM_ROUTE(ROUTE_ID),
    CONSTRAINT FK_FFA_ACFT  FOREIGN KEY (AIRCRAFT_ID)            REFERENCES DIM_AIRCRAFT(AIRCRAFT_ID)
    -- CONSTRAINT FK_FFA_ORIG  FOREIGN KEY (ORIGIN_AIRPORT_ID)      REFERENCES DIM_AIRPORT(AIRPORT_ID),
    -- CONSTRAINT FK_FFA_DEST  FOREIGN KEY (DESTINATION_AIRPORT_ID) REFERENCES DIM_AIRPORT(AIRPORT_ID)
)
PARTITION BY RANGE (DATE_KEY)
(
    PARTITION P_2023 VALUES LESS THAN (20240101),
    PARTITION P_2024 VALUES LESS THAN (20250101),
    PARTITION P_2025 VALUES LESS THAN (20260101),
    PARTITION P_2026 VALUES LESS THAN (20270101),
    PARTITION P_MAX  VALUES LESS THAN (MAXVALUE) 
);

CREATE OR REPLACE TRIGGER TRG_FACT_FLIGHT_PK
BEFORE INSERT ON FACT_FLIGHT_ACTIVITY
FOR EACH ROW
BEGIN
    IF :NEW.FACT_FLIGHT_ID IS NULL THEN
        SELECT SEQ_FACT_FLIGHT.NEXTVAL INTO :NEW.FACT_FLIGHT_ID FROM DUAL;
    END IF;
END;
/

-- Grain: one row per reservation (merged with ticket — same grain, same dims).
-- Business process: reservation & revenue.
-- RESERVATION + TICKET + PAYMENT joined at ETL time.
-- FLIGHT_COSTS allocated per reservation via FLIGHT_ID link.
CREATE TABLE FACT_RESERVATION (
    FACT_RESERVATION_ID      NUMBER          NOT NULL,
    -- Degenerate dimensions
    RESERVATION_ID           NUMBER          NOT NULL,
    TICKET_ID                NUMBER          NULL,
    TICKET_NUMBER            VARCHAR2(30)    NULL,
    SEAT_NUMBER              VARCHAR2(10)    NULL,
    RESERVATION_STATUS       VARCHAR2(30)    NULL,
    TICKET_STATUS            VARCHAR2(30)    NULL,
    IS_UPGRADE               VARCHAR2(1)     DEFAULT 'N' NULL,
    -- FK to dimensions (natural keys)
    BOOKING_DATE_KEY         NUMBER(8)       NOT NULL,   -- FK DIM_DATE
    TICKET_ISSUE_DATE_KEY    NUMBER(8)       NULL,       -- FK DIM_DATE
    PASSENGER_SK             NUMBER          NOT NULL,   -- FK DIM_PASSENGER (SCD2 SK)
    FLIGHT_ID                NUMBER          NOT NULL,   -- links to FACT_FLIGHT_ACTIVITY
    ROUTE_ID                 NUMBER          NOT NULL,   -- FK DIM_ROUTE
    FARE_CLASS_ID            NUMBER          NOT NULL,   -- FK DIM_FARE_CLASS
    CHANNEL_ID               NUMBER          NOT NULL,   -- FK DIM_BOOKING_CHANNEL
    PROMO_ID                 NUMBER          NULL,       -- FK DIM_PROMOTION (nullable)
    -- Payment detail
    PAYMENT_METHOD           VARCHAR2(40)    NULL,
    PAYMENT_STATUS           VARCHAR2(30)    NULL,
    PAYMENT_AMOUNT_USD       NUMBER(10,2)    NULL,
    CURRENCY_CODE            VARCHAR2(3)     NULL,
    TRANSACTION_REFERENCE    VARCHAR2(50)    NULL,
    -- Revenue measures
    AMOUNT_PAID              NUMBER(10,2)    NULL,
    BASE_FARE_USD            NUMBER(10,2)    NULL,
    TAX_AMOUNT_USD           NUMBER(10,2)    NULL,
    FEE_AMOUNT_USD           NUMBER(10,2)    NULL,
    DISCOUNT_AMOUNT_USD      NUMBER(10,2)    NULL,
    FINAL_TICKET_AMOUNT_USD  NUMBER(10,2)    NULL,
    -- Miles measures
    MILES_EARNED             NUMBER          NULL,
    MILES_REDEEMED           NUMBER          NULL,
    -- Profit (computed at ETL time)
    PROFIT_USD               NUMBER(10,2)    NULL,   -- final_ticket_amount - allocated flight cost
    -- ETL metadata
    ETL_LOAD_DATE            DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_FACT_RES PRIMARY KEY (FACT_RESERVATION_ID),
    CONSTRAINT FK_RES_BDATE FOREIGN KEY (BOOKING_DATE_KEY)   REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_RES_TDATE FOREIGN KEY (TICKET_ISSUE_DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_RES_PASS  FOREIGN KEY (PASSENGER_SK)       REFERENCES DIM_PASSENGER(PASSENGER_SK),
    CONSTRAINT FK_RES_ROUTE FOREIGN KEY (ROUTE_ID)           REFERENCES DIM_ROUTE(ROUTE_ID),
    CONSTRAINT FK_RES_FARE  FOREIGN KEY (FARE_CLASS_ID)      REFERENCES DIM_FARE_CLASS(FARE_CLASS_ID),
    CONSTRAINT FK_RES_CHAN  FOREIGN KEY (CHANNEL_ID)         REFERENCES DIM_BOOKING_CHANNEL(CHANNEL_ID),
    CONSTRAINT FK_RES_PROMO FOREIGN KEY (PROMO_ID)           REFERENCES DIM_PROMOTION(PROMO_ID)
)
PARTITION BY RANGE (BOOKING_DATE_KEY)
(
    PARTITION P_2023 VALUES LESS THAN (20240101),
    PARTITION P_2024 VALUES LESS THAN (20250101),
    PARTITION P_2025 VALUES LESS THAN (20260101),
    PARTITION P_2026 VALUES LESS THAN (20270101),
    PARTITION P_MAX  VALUES LESS THAN (MAXVALUE)   
);

CREATE OR REPLACE TRIGGER TRG_FACT_RES_PK
BEFORE INSERT ON FACT_RESERVATION
FOR EACH ROW
BEGIN
    IF :NEW.FACT_RESERVATION_ID IS NULL THEN
        SELECT SEQ_FACT_RES.NEXTVAL INTO :NEW.FACT_RESERVATION_ID FROM DUAL;
    END IF;
END;
/


-- Grain: one row per loyalty miles transaction.
-- Business process: miles earning, redemption, expiry, adjustments.
-- Source: LOYALTY_MILES_TRANSACTIONS.csv
CREATE TABLE FACT_LOYALTY_MILES (
    FACT_LOYALTY_ID        NUMBER          NOT NULL,
    -- Degenerate dimensions
    TRANSACTION_ID         NUMBER          NOT NULL,
    FF_NUMBER              VARCHAR2(20)    NULL,
    RESERVATION_ID         NUMBER          NULL,
    TRANSACTION_TYPE       VARCHAR2(20)    NOT NULL,  -- EARN/REDEEM/BONUS/EXPIRE/ADJUSTMENT
    SOURCE_SYSTEM          VARCHAR2(40)    NULL,
    DESCRIPTION            VARCHAR2(200)   NULL,
    -- FK to dimensions
    TRANSACTION_DATE_KEY   NUMBER(8)       NOT NULL,  -- FK DIM_DATE
    PASSENGER_SK           NUMBER          NOT NULL,  -- FK DIM_PASSENGER (SCD2)
    -- Measures
    MILES_AMOUNT           NUMBER          NOT NULL,  -- negative for REDEEM/EXPIRE
    ETL_LOAD_DATE          DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_FACT_LOYALTY PRIMARY KEY (FACT_LOYALTY_ID),
    CONSTRAINT FK_LOY_DATE FOREIGN KEY (TRANSACTION_DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_LOY_PASS FOREIGN KEY (PASSENGER_SK)         REFERENCES DIM_PASSENGER(PASSENGER_SK)
)
PARTITION BY RANGE (TRANSACTION_DATE_KEY)
(
    PARTITION P_2023 VALUES LESS THAN (20240101),
    PARTITION P_2024 VALUES LESS THAN (20250101),
    PARTITION P_2025 VALUES LESS THAN (20260101),
    PARTITION P_2026 VALUES LESS THAN (20270101),
    PARTITION P_MAX  VALUES LESS THAN (MAXVALUE)   
);

CREATE OR REPLACE TRIGGER TRG_FACT_LOYALTY_PK
BEFORE INSERT ON FACT_LOYALTY_MILES
FOR EACH ROW
BEGIN
    IF :NEW.FACT_LOYALTY_ID IS NULL THEN
        SELECT SEQ_FACT_LOYALTY.NEXTVAL INTO :NEW.FACT_LOYALTY_ID FROM DUAL;
    END IF;
END;
/


-- Grain: one row per customer care interaction.
-- Business process: customer care — complaints, inquiries, feedback.
-- Source: CUSTOMER_INTERACTIONS.csv
-- NOTE: CSV has JOURNEY_PHASE (PRE_TRIP/IN_TRIP/POST_TRIP) not in original spec — included.
CREATE TABLE FACT_CUSTOMER_INTERACTION (
    FACT_INTERACTION_ID    NUMBER          NOT NULL,
    -- Degenerate dimensions
    INTERACTION_ID         NUMBER          NOT NULL,
    RESERVATION_ID         NUMBER          NULL,
    JOURNEY_PHASE          VARCHAR2(20)    NULL,   -- PRE_TRIP / IN_TRIP / POST_TRIP
    INTERACTION_TYPE       VARCHAR2(50)    NULL,   -- complaint / inquiry / feedback
    CHANNEL                VARCHAR2(50)    NULL,   -- phone / email / chat
    ISSUE_CATEGORY         VARCHAR2(80)    NULL,
    SEVERITY               VARCHAR2(20)    NULL,   -- low / medium / high / critical
    DESCRIPTION            VARCHAR2(500)   NULL,
    RESOLUTION_STATUS      VARCHAR2(40)    NULL,
    -- FK to dimensions
    INTERACTION_DATE_KEY   NUMBER(8)       NOT NULL,  -- FK DIM_DATE
    RESOLUTION_DATE_KEY    NUMBER(8)       NULL,      -- FK DIM_DATE (null if unresolved)
    PASSENGER_SK           NUMBER          NOT NULL,  -- FK DIM_PASSENGER (SCD2)
    -- Measures
    CSAT_SCORE             NUMBER(3,1)     NULL,
    RESOLUTION_DAYS        NUMBER          NULL,  -- resolution_date - interaction_date
    ETL_LOAD_DATE          DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_FACT_INTERACT PRIMARY KEY (FACT_INTERACTION_ID),
    CONSTRAINT FK_INT_IDATE FOREIGN KEY (INTERACTION_DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_INT_RDATE FOREIGN KEY (RESOLUTION_DATE_KEY)  REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_INT_PASS  FOREIGN KEY (PASSENGER_SK)         REFERENCES DIM_PASSENGER(PASSENGER_SK)
)
PARTITION BY RANGE (INTERACTION_DATE_KEY)
(
    PARTITION P_2023 VALUES LESS THAN (20240101),
    PARTITION P_2024 VALUES LESS THAN (20250101),
    PARTITION P_2025 VALUES LESS THAN (20260101),
    PARTITION P_2026 VALUES LESS THAN (20270101),
    PARTITION P_MAX  VALUES LESS THAN (MAXVALUE)   
);

CREATE OR REPLACE TRIGGER TRG_FACT_INTERACT_PK
BEFORE INSERT ON FACT_CUSTOMER_INTERACTION
FOR EACH ROW
BEGIN
    IF :NEW.FACT_INTERACTION_ID IS NULL THEN
        SELECT SEQ_FACT_INTERACT.NEXTVAL INTO :NEW.FACT_INTERACTION_ID FROM DUAL;
    END IF;
END;
/

-- Grain: one row per promotion sent to one passenger.
-- Business process: promotion response tracking.
-- Source: PROMOTION_RESPONSES.csv
-- Measures are row-level FLAGS, not pre-aggregated counts.
-- Counts are computed at query time (COUNT WHERE flag='Y').
CREATE TABLE FACT_PROMOTION_RESPONSE (
    FACT_PROMO_RESP_ID     NUMBER          NOT NULL,
    -- Degenerate dimensions
    RESPONSE_ID            NUMBER          NOT NULL,
    RESERVATION_ID         NUMBER          NULL,   -- populated if BOOKED_FLAG='Y'
    COMMUNICATION_CHANNEL  VARCHAR2(50)    NULL,   -- email / SMS / push notification
    -- FK to dimensions
    SENT_DATE_KEY          NUMBER(8)       NOT NULL,  -- FK DIM_DATE
    PASSENGER_SK           NUMBER          NOT NULL,  -- FK DIM_PASSENGER (SCD2)
    PROMO_ID               NUMBER          NOT NULL,  -- FK DIM_PROMOTION
    -- Measures / row-level flags
    OPENED_FLAG            VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    CLICKED_FLAG           VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    BOOKED_FLAG            VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    ETL_LOAD_DATE          DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_FACT_PROMO_RESP PRIMARY KEY (FACT_PROMO_RESP_ID),
    CONSTRAINT FK_PR_DATE  FOREIGN KEY (SENT_DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_PR_PASS  FOREIGN KEY (PASSENGER_SK)  REFERENCES DIM_PASSENGER(PASSENGER_SK),
    CONSTRAINT FK_PR_PROMO FOREIGN KEY (PROMO_ID)      REFERENCES DIM_PROMOTION(PROMO_ID)
)
PARTITION BY RANGE (SENT_DATE_KEY)
(
    PARTITION P_2023 VALUES LESS THAN (20240101),
    PARTITION P_2024 VALUES LESS THAN (20250101),
    PARTITION P_2025 VALUES LESS THAN (20260101),
    PARTITION P_2026 VALUES LESS THAN (20270101),
    PARTITION P_MAX  VALUES LESS THAN (MAXVALUE)   
);

CREATE OR REPLACE TRIGGER TRG_FACT_PROMO_PK
BEFORE INSERT ON FACT_PROMOTION_RESPONSE
FOR EACH ROW
BEGIN
    IF :NEW.FACT_PROMO_RESP_ID IS NULL THEN
        SELECT SEQ_FACT_PROMO.NEXTVAL INTO :NEW.FACT_PROMO_RESP_ID FROM DUAL;
    END IF;
END;
/

-- Grain: one row per upgrade request.
-- Business process: upgrade tracking (paid vs miles).
-- Source: FLIGHT_UPGRADES.csv
-- NOTE: CSV has extra columns vs spec: REQUEST_DATE, DECISION_DATE,
--       REQUEST_CHANNEL, REJECTION_REASON — all included.
CREATE TABLE FACT_FLIGHT_UPGRADE (
    FACT_UPGRADE_ID        NUMBER          NOT NULL,
    -- Degenerate dimensions
    UPGRADE_ID             NUMBER          NOT NULL,
    RESERVATION_ID         NUMBER          NOT NULL,
    FROM_CLASS             VARCHAR2(30)    NULL,   -- cabin before upgrade
    TO_CLASS               VARCHAR2(30)    NULL,   -- cabin after upgrade
    UPGRADE_TYPE           VARCHAR2(30)    NULL,   -- PAID_UPGRADE / MILES_UPGRADE
    REQUEST_CHANNEL        VARCHAR2(50)    NULL,   -- AIRPORT_COUNTER / MOBILE_APP / CALL_CENTER...
    REJECTION_REASON       VARCHAR2(200)   NULL,   -- populated if STATUS = REJECTED
    UPGRADE_STATUS         VARCHAR2(30)    NULL,   -- COMPLETED / REJECTED / PENDING
    -- FK to dimensions
    REQUEST_DATE_KEY       NUMBER(8)       NOT NULL,  -- FK DIM_DATE
    DECISION_DATE_KEY      NUMBER(8)       NULL,      -- FK DIM_DATE
    UPGRADE_DATE_KEY       NUMBER(8)       NULL,      -- FK DIM_DATE
    PASSENGER_SK           NUMBER          NOT NULL,  -- FK DIM_PASSENGER (SCD2)
    -- Measures
    MILES_USED             NUMBER          DEFAULT 0 NULL,
    AMOUNT_PAID            NUMBER(10,2)    DEFAULT 0 NULL,
    ETL_LOAD_DATE          DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_FACT_UPGRADE PRIMARY KEY (FACT_UPGRADE_ID),
    CONSTRAINT FK_UPG_RDATE FOREIGN KEY (REQUEST_DATE_KEY)  REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_UPG_DDATE FOREIGN KEY (DECISION_DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_UPG_UDATE FOREIGN KEY (UPGRADE_DATE_KEY)  REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_UPG_PASS  FOREIGN KEY (PASSENGER_SK)      REFERENCES DIM_PASSENGER(PASSENGER_SK)
)
PARTITION BY RANGE (REQUEST_DATE_KEY)
(
    PARTITION P_2023 VALUES LESS THAN (20240101),
    PARTITION P_2024 VALUES LESS THAN (20250101),
    PARTITION P_2025 VALUES LESS THAN (20260101),
    PARTITION P_2026 VALUES LESS THAN (20270101),
    PARTITION P_MAX  VALUES LESS THAN (MAXVALUE)   
);

CREATE OR REPLACE TRIGGER TRG_FACT_UPGRADE_PK
BEFORE INSERT ON FACT_FLIGHT_UPGRADE
FOR EACH ROW
BEGIN
    IF :NEW.FACT_UPGRADE_ID IS NULL THEN
        SELECT SEQ_FACT_UPGRADE.NEXTVAL INTO :NEW.FACT_UPGRADE_ID FROM DUAL;
    END IF;
END;
/

-- Grain: one row per hotel stay linked to a reservation.
-- Business process: overnight stay tracking.
-- Source: OVERNIGHT_STAYS.csv
CREATE TABLE FACT_OVERNIGHT_STAY (
    FACT_STAY_ID           NUMBER          NOT NULL,
    -- Degenerate dimensions
    STAY_ID                NUMBER          NOT NULL,
    RESERVATION_ID         NUMBER          NOT NULL,
    HOTEL_NAME             VARCHAR2(100)   NULL,
    CITY                   VARCHAR2(80)    NULL,
    COUNTRY                VARCHAR2(80)    NULL,
    ROOM_TYPE              VARCHAR2(50)    NULL,
    PAID_BY_AIRLINE        VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    -- FK to dimensions
    CHECK_IN_DATE_KEY      NUMBER(8)       NOT NULL,  -- FK DIM_DATE
    CHECK_OUT_DATE_KEY     NUMBER(8)       NOT NULL,  -- FK DIM_DATE
    PASSENGER_SK           NUMBER          NOT NULL,  -- FK DIM_PASSENGER (SCD2)
    -- Measures
    NIGHTS                 NUMBER          NOT NULL,
    NIGHTLY_RATE_USD       NUMBER(10,2)    NULL,
    TOTAL_STAY_COST_USD    NUMBER(10,2)    NULL,  -- derived: NIGHTS * NIGHTLY_RATE_USD
    ETL_LOAD_DATE          DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_FACT_STAY PRIMARY KEY (FACT_STAY_ID),
    CONSTRAINT FK_STAY_CHKIN  FOREIGN KEY (CHECK_IN_DATE_KEY)  REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_STAY_CHKOUT FOREIGN KEY (CHECK_OUT_DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_STAY_PASS   FOREIGN KEY (PASSENGER_SK)       REFERENCES DIM_PASSENGER(PASSENGER_SK)
)
PARTITION BY RANGE (CHECK_IN_DATE_KEY)
(
    PARTITION P_2023 VALUES LESS THAN (20240101),
    PARTITION P_2024 VALUES LESS THAN (20250101),
    PARTITION P_2025 VALUES LESS THAN (20260101),
    PARTITION P_2026 VALUES LESS THAN (20270101),
    PARTITION P_MAX  VALUES LESS THAN (MAXVALUE)  
);

CREATE OR REPLACE TRIGGER TRG_FACT_STAY_PK
BEFORE INSERT ON FACT_OVERNIGHT_STAY
FOR EACH ROW
BEGIN
    IF :NEW.FACT_STAY_ID IS NULL THEN
        SELECT SEQ_FACT_STAY.NEXTVAL INTO :NEW.FACT_STAY_ID FROM DUAL;
    END IF;
END;
/

-- DIM_PASSENGER: ETL lookups by natural key and current flag
CREATE INDEX IDX_DIM_PASS_ID    ON DIM_PASSENGER(PASSENGER_ID);
CREATE INDEX IDX_DIM_PASS_CURR  ON DIM_PASSENGER(PASSENGER_ID, IS_CURRENT);
CREATE INDEX IDX_DIM_PASS_FF    ON DIM_PASSENGER(FF_NUMBER);

-- DIM_ROUTE: ETL and query lookups by airport
CREATE INDEX IDX_ROUTE_ORIG     ON DIM_ROUTE(ORIGIN_AIRPORT_ID);
CREATE INDEX IDX_ROUTE_DEST     ON DIM_ROUTE(DESTINATION_AIRPORT_ID);

-- FACT_FLIGHT_ACTIVITY (LOCAL = partition-aware)
CREATE INDEX IDX_FFA_DATE     ON FACT_FLIGHT_ACTIVITY(DATE_KEY) LOCAL;
CREATE INDEX IDX_FFA_ROUTE    ON FACT_FLIGHT_ACTIVITY(ROUTE_ID) LOCAL;
CREATE INDEX IDX_FFA_AIRCRAFT ON FACT_FLIGHT_ACTIVITY(AIRCRAFT_ID) LOCAL;
CREATE INDEX IDX_FFA_FLIGHT   ON FACT_FLIGHT_ACTIVITY(FLIGHT_ID) LOCAL;
-- CREATE INDEX IDX_FFA_ORIG       ON FACT_FLIGHT_ACTIVITY(ORIGIN_AIRPORT_ID)      LOCAL;
-- CREATE INDEX IDX_FFA_DEST       ON FACT_FLIGHT_ACTIVITY(DESTINATION_AIRPORT_ID) LOCAL;

-- FACT_RESERVATION
CREATE INDEX IDX_FR_BDATE   ON FACT_RESERVATION(BOOKING_DATE_KEY) LOCAL;
CREATE INDEX IDX_FR_PASS    ON FACT_RESERVATION(PASSENGER_SK) LOCAL;
CREATE INDEX IDX_FR_ROUTE   ON FACT_RESERVATION(ROUTE_ID) LOCAL;
CREATE INDEX IDX_FR_CHANNEL ON FACT_RESERVATION(CHANNEL_ID) LOCAL;
CREATE INDEX IDX_FR_PROMO   ON FACT_RESERVATION(PROMO_ID) LOCAL;
CREATE INDEX IDX_FR_RESID   ON FACT_RESERVATION(RESERVATION_ID) LOCAL;
CREATE INDEX IDX_FR_FLIGHT  ON FACT_RESERVATION(FLIGHT_ID) LOCAL;

-- FACT_LOYALTY_MILES
CREATE INDEX IDX_FL_DATE  ON FACT_LOYALTY_MILES(TRANSACTION_DATE_KEY) LOCAL;
CREATE INDEX IDX_FL_PASS  ON FACT_LOYALTY_MILES(PASSENGER_SK) LOCAL;
CREATE INDEX IDX_FL_TYPE  ON FACT_LOYALTY_MILES(TRANSACTION_TYPE) LOCAL;
CREATE INDEX IDX_FL_RESID ON FACT_LOYALTY_MILES(RESERVATION_ID) LOCAL;

-- FACT_CUSTOMER_INTERACTION
CREATE INDEX IDX_FCI_DATE  ON FACT_CUSTOMER_INTERACTION(INTERACTION_DATE_KEY) LOCAL;
CREATE INDEX IDX_FCI_PASS  ON FACT_CUSTOMER_INTERACTION(PASSENGER_SK) LOCAL;
CREATE INDEX IDX_FCI_SEV   ON FACT_CUSTOMER_INTERACTION(SEVERITY) LOCAL;
CREATE INDEX IDX_FCI_RESID ON FACT_CUSTOMER_INTERACTION(RESERVATION_ID) LOCAL;

-- FACT_PROMOTION_RESPONSE
CREATE INDEX IDX_FPR_DATE  ON FACT_PROMOTION_RESPONSE(SENT_DATE_KEY) LOCAL;
CREATE INDEX IDX_FPR_PASS  ON FACT_PROMOTION_RESPONSE(PASSENGER_SK) LOCAL;
CREATE INDEX IDX_FPR_PROMO ON FACT_PROMOTION_RESPONSE(PROMO_ID) LOCAL;

-- FACT_FLIGHT_UPGRADE
CREATE INDEX IDX_FUG_RDATE ON FACT_FLIGHT_UPGRADE(REQUEST_DATE_KEY) LOCAL;
CREATE INDEX IDX_FUG_PASS  ON FACT_FLIGHT_UPGRADE(PASSENGER_SK) LOCAL;
CREATE INDEX IDX_FUG_TYPE  ON FACT_FLIGHT_UPGRADE(UPGRADE_TYPE) LOCAL;
CREATE INDEX IDX_FUG_RESID ON FACT_FLIGHT_UPGRADE(RESERVATION_ID) LOCAL;

-- FACT_OVERNIGHT_STAY
CREATE INDEX IDX_FOS_DATE  ON FACT_OVERNIGHT_STAY(CHECK_IN_DATE_KEY) LOCAL;
CREATE INDEX IDX_FOS_PASS  ON FACT_OVERNIGHT_STAY(PASSENGER_SK) LOCAL;
CREATE INDEX IDX_FOS_RESID ON FACT_OVERNIGHT_STAY(RESERVATION_ID) LOCAL;























