/* ============================================================
   1. DIMENSION TABLES
   ============================================================ */

CREATE TABLE DIM_DATE (
    DATE_KEY NUMBER PRIMARY KEY,
    FULL_DATE DATE NOT NULL,
    DAY_NUMBER NUMBER,
    DAY_NAME VARCHAR2(20),
    MONTH_NUMBER NUMBER,
    MONTH_NAME VARCHAR2(20),
    QUARTER_NUMBER NUMBER,
    YEAR_NUMBER NUMBER,
    WEEK_NUMBER NUMBER,
    IS_WEEKEND VARCHAR2(1)
);

CREATE TABLE DIM_AIRPORT (
    AIRPORT_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AIRPORT_ID NUMBER,
    IATA_CODE VARCHAR2(3),
    AIRPORT_NAME VARCHAR2(120),
    CITY VARCHAR2(80),
    COUNTRY VARCHAR2(80),
    TIMEZONE VARCHAR2(80),
    TERMINAL_COUNT NUMBER
);

CREATE TABLE DIM_AIRCRAFT (
    AIRCRAFT_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AIRCRAFT_ID NUMBER,
    TAIL_NUMBER VARCHAR2(20),
    MODEL VARCHAR2(80),
    MANUFACTURER VARCHAR2(80),
    CAPACITY_ECONOMY NUMBER,
    CAPACITY_BUSINESS NUMBER,
    CAPACITY_FIRST NUMBER,
    YEAR_MANUFACTURED NUMBER,
    STATUS VARCHAR2(30)
);

CREATE TABLE DIM_ROUTE (
    ROUTE_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROUTE_ID NUMBER,
    ORIGIN_AIRPORT_ID NUMBER,
    DESTINATION_AIRPORT_ID NUMBER,
    DISTANCE_KM NUMBER,
    FLIGHT_DURATION_MIN NUMBER,
    IS_INTERNATIONAL VARCHAR2(1),
    BASE_PRICE_USD NUMBER(10,2)
);

CREATE TABLE DIM_FLIGHT (
    FLIGHT_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FLIGHT_ID NUMBER,
    FLIGHT_NUMBER VARCHAR2(10),
    ROUTE_ID NUMBER,
    AIRCRAFT_ID NUMBER,
    SCHEDULED_DEPARTURE TIMESTAMP,
    SCHEDULED_ARRIVAL TIMESTAMP,
    ACTUAL_DEPARTURE TIMESTAMP,
    ACTUAL_ARRIVAL TIMESTAMP,
    STATUS VARCHAR2(30)
);

CREATE TABLE DIM_FARE_CLASS (
    FARE_CLASS_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FARE_CLASS_ID NUMBER,
    FARE_CODE VARCHAR2(5),
    FARE_DESCRIPTION VARCHAR2(80),
    CABIN VARCHAR2(30),
    REFUNDABLE VARCHAR2(1),
    MILES_MULTIPLIER NUMBER(5,2)
);

CREATE TABLE DIM_BOOKING_CHANNEL (
    CHANNEL_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CHANNEL_ID NUMBER,
    CHANNEL_NAME VARCHAR2(50),
    CHANNEL_TYPE VARCHAR2(50),
    IS_ONLINE VARCHAR2(1)
);

CREATE TABLE DIM_FREQUENT_FLYER_TIER (
    TIER_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIER_ID NUMBER,
    TIER_NAME VARCHAR2(30),
    MIN_MILES NUMBER,
    LOUNGE_ACCESS VARCHAR2(1),
    PRIORITY_BOARDING VARCHAR2(1),
    UPGRADE_ELIGIBLE VARCHAR2(1),
    BONUS_MILES_PCT NUMBER(5,2)
);

CREATE TABLE DIM_PASSENGER (
    PASSENGER_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PASSENGER_ID NUMBER,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    GENDER VARCHAR2(1),
    DATE_OF_BIRTH DATE,
    NATIONALITY VARCHAR2(50),
    PASSPORT_NUMBER VARCHAR2(30),
    EMAIL VARCHAR2(120),
    PHONE VARCHAR2(40),
    FF_NUMBER VARCHAR2(20),
    TIER_ID NUMBER,
    TOTAL_MILES NUMBER,
    JOIN_DATE DATE,
    EFFECTIVE_START_DATE DATE,
    EFFECTIVE_END_DATE DATE,
    CURRENT_FLAG VARCHAR2(1),
    VERSION_NUMBER NUMBER
);

CREATE TABLE DIM_PROMOTION (
    PROMOTION_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROMO_ID NUMBER,
    PROMO_CODE VARCHAR2(30),
    PROMO_NAME VARCHAR2(100),
    DISCOUNT_PCT NUMBER(10,2),
    MILES_BONUS VARCHAR2(50),
    START_DATE DATE,
    END_DATE DATE,
    ROUTE_ID NUMBER,
    IS_ACTIVE VARCHAR2(1)
);

CREATE TABLE DIM_HOTEL (
    HOTEL_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HOTEL_NAME VARCHAR2(120),
    CITY VARCHAR2(80),
    COUNTRY VARCHAR2(80)
);

/* ============================================================
   2. FACT TABLES
   ============================================================ */

CREATE TABLE FACT_RESERVATION (
    RESERVATION_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RESERVATION_ID NUMBER,
    PASSENGER_KEY NUMBER,
    FLIGHT_KEY NUMBER,
    FARE_CLASS_KEY NUMBER,
    CHANNEL_KEY NUMBER,
    PROMOTION_KEY NUMBER,
    BOOKING_DATE_KEY NUMBER,
    AMOUNT_PAID NUMBER(10,2),
    MILES_EARNED NUMBER,
    MILES_REDEEMED NUMBER,
    IS_UPGRADE VARCHAR2(1),
    RESERVATION_COUNT NUMBER DEFAULT 1,
    STATUS VARCHAR2(30),
    BATCH_ID NUMBER,
    LOAD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
)
PARTITION BY RANGE (BOOKING_DATE_KEY)
(
    PARTITION P_2024 VALUES LESS THAN (20250101),
    PARTITION P_2025 VALUES LESS THAN (20260101),
    PARTITION P_2026 VALUES LESS THAN (20270101),
    PARTITION P_FUTURE VALUES LESS THAN (MAXVALUE)
);

CREATE TABLE FACT_TICKET_REVENUE (
    TICKET_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TICKET_ID NUMBER,
    TICKET_NUMBER VARCHAR2(30),
    RESERVATION_ID NUMBER,
    PASSENGER_KEY NUMBER,
    FLIGHT_KEY NUMBER,
    FARE_CLASS_KEY NUMBER,
    ISSUE_DATE_KEY NUMBER,
    BASE_FARE_USD NUMBER(10,2),
    TAX_AMOUNT_USD NUMBER(10,2),
    FEE_AMOUNT_USD NUMBER(10,2),
    DISCOUNT_AMOUNT_USD NUMBER(10,2),
    FINAL_TICKET_AMOUNT_USD NUMBER(10,2),
    MILES_EARNED NUMBER,
    MILES_REDEEMED NUMBER,
    TICKET_COUNT NUMBER DEFAULT 1,
    TICKET_STATUS VARCHAR2(30),
    BATCH_ID NUMBER,
    LOAD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
)
PARTITION BY RANGE (ISSUE_DATE_KEY)
(
    PARTITION P_2024 VALUES LESS THAN (20250101),
    PARTITION P_2025 VALUES LESS THAN (20260101),
    PARTITION P_2026 VALUES LESS THAN (20270101),
    PARTITION P_FUTURE VALUES LESS THAN (MAXVALUE)
);

CREATE TABLE FACT_FLIGHT_PROFITABILITY (
    FLIGHT_PROFIT_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FLIGHT_KEY NUMBER,
    ROUTE_KEY NUMBER,
    FLIGHT_DATE_KEY NUMBER,
    REVENUE_USD NUMBER(12,2),
    FUEL_COST_USD NUMBER(10,2),
    CREW_COST_USD NUMBER(10,2),
    AIRPORT_FEES_USD NUMBER(10,2),
    MAINTENANCE_COST_USD NUMBER(10,2),
    CATERING_COST_USD NUMBER(10,2),
    TOTAL_COST_USD NUMBER(12,2),
    PROFIT_USD NUMBER(12,2),
    PROFIT_MARGIN_PCT NUMBER(10,2),
    BATCH_ID NUMBER,
    LOAD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
)
PARTITION BY RANGE (FLIGHT_DATE_KEY)
(
    PARTITION P_2024 VALUES LESS THAN (20250101),
    PARTITION P_2025 VALUES LESS THAN (20260101),
    PARTITION P_2026 VALUES LESS THAN (20270101),
    PARTITION P_FUTURE VALUES LESS THAN (MAXVALUE)
);

CREATE TABLE FACT_LOYALTY_MILES (
    LOYALTY_FACT_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRANSACTION_ID NUMBER,
    PASSENGER_KEY NUMBER,
    RESERVATION_ID NUMBER,
    TRANSACTION_DATE_KEY NUMBER,
    TRANSACTION_TYPE VARCHAR2(30),
    MILES_EARNED NUMBER DEFAULT 0,
    MILES_REDEEMED NUMBER DEFAULT 0,
    MILES_BONUS NUMBER DEFAULT 0,
    MILES_EXPIRED NUMBER DEFAULT 0,
    MILES_ADJUSTMENT NUMBER DEFAULT 0,
    TRANSACTION_COUNT NUMBER DEFAULT 1,
    BATCH_ID NUMBER,
    LOAD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
)
PARTITION BY RANGE (TRANSACTION_DATE_KEY)
(
    PARTITION P_2024 VALUES LESS THAN (20250101),
    PARTITION P_2025 VALUES LESS THAN (20260101),
    PARTITION P_2026 VALUES LESS THAN (20270101),
    PARTITION P_FUTURE VALUES LESS THAN (MAXVALUE)
);

CREATE TABLE FACT_PROMOTION_RESPONSE (
    PROMOTION_RESPONSE_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RESPONSE_ID NUMBER,
    PASSENGER_KEY NUMBER,
    PROMOTION_KEY NUMBER,
    RESERVATION_ID NUMBER,
    SENT_DATE_KEY NUMBER,
    COMMUNICATION_CHANNEL VARCHAR2(50),
    SENT_COUNT NUMBER DEFAULT 1,
    OPENED_COUNT NUMBER,
    CLICKED_COUNT NUMBER,
    BOOKED_COUNT NUMBER,
    BATCH_ID NUMBER,
    LOAD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
)
PARTITION BY RANGE (SENT_DATE_KEY)
(
    PARTITION P_2024 VALUES LESS THAN (20250101),
    PARTITION P_2025 VALUES LESS THAN (20260101),
    PARTITION P_2026 VALUES LESS THAN (20270101),
    PARTITION P_FUTURE VALUES LESS THAN (MAXVALUE)
);

CREATE TABLE FACT_FLIGHT_UPGRADE (
    UPGRADE_FACT_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UPGRADE_ID NUMBER,
    RESERVATION_ID NUMBER,
    PASSENGER_KEY NUMBER,
    UPGRADE_DATE_KEY NUMBER,
    FROM_CLASS VARCHAR2(30),
    TO_CLASS VARCHAR2(30),
    UPGRADE_TYPE VARCHAR2(50),
    MILES_USED NUMBER,
    AMOUNT_PAID NUMBER(10,2),
    STATUS VARCHAR2(30),
    UPGRADE_COUNT NUMBER DEFAULT 1,
    BATCH_ID NUMBER,
    LOAD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE FACT_OVERNIGHT_STAY (
    OVERNIGHT_FACT_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STAY_ID NUMBER,
    RESERVATION_ID NUMBER,
    PASSENGER_KEY NUMBER,
    HOTEL_KEY NUMBER,
    CHECK_IN_DATE_KEY NUMBER,
    CHECK_OUT_DATE_KEY NUMBER,
    NIGHTS NUMBER,
    ROOM_TYPE VARCHAR2(50),
    NIGHTLY_RATE_USD NUMBER(10,2),
    STAY_COST_USD NUMBER(10,2),
    PAID_BY_AIRLINE VARCHAR2(1),
    STAY_COUNT NUMBER DEFAULT 1,
    BATCH_ID NUMBER,
    LOAD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE FACT_CUSTOMER_INTERACTION (
    INTERACTION_FACT_KEY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INTERACTION_ID NUMBER,
    PASSENGER_KEY NUMBER,
    RESERVATION_ID NUMBER,
    INTERACTION_DATE_KEY NUMBER,
    INTERACTION_TYPE VARCHAR2(50),
    CHANNEL VARCHAR2(50),
    ISSUE_CATEGORY VARCHAR2(80),
    SEVERITY VARCHAR2(30),
    RESOLUTION_STATUS VARCHAR2(50),
    RESOLUTION_TIME_DAYS NUMBER,
    CSAT_SCORE NUMBER,
    INTERACTION_COUNT NUMBER DEFAULT 1,
    BATCH_ID NUMBER,
    LOAD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

/* ============================================================
   7. INDEXES
   ============================================================ */

/* Dimension natural key indexes */

CREATE INDEX IDX_DIM_AIRPORT_NK ON DIM_AIRPORT(AIRPORT_ID);
CREATE INDEX IDX_DIM_AIRCRAFT_NK ON DIM_AIRCRAFT(AIRCRAFT_ID);
CREATE INDEX IDX_DIM_ROUTE_NK ON DIM_ROUTE(ROUTE_ID);
CREATE INDEX IDX_DIM_FLIGHT_NK ON DIM_FLIGHT(FLIGHT_ID);
CREATE INDEX IDX_DIM_FARE_CLASS_NK ON DIM_FARE_CLASS(FARE_CLASS_ID);
CREATE INDEX IDX_DIM_CHANNEL_NK ON DIM_BOOKING_CHANNEL(CHANNEL_ID);
CREATE INDEX IDX_DIM_TIER_NK ON DIM_FREQUENT_FLYER_TIER(TIER_ID);
CREATE INDEX IDX_DIM_PROMOTION_NK ON DIM_PROMOTION(PROMO_ID);

CREATE INDEX IDX_DIM_PASSENGER_NK 
ON DIM_PASSENGER(PASSENGER_ID, CURRENT_FLAG);

CREATE INDEX IDX_DIM_PASSENGER_FF 
ON DIM_PASSENGER(FF_NUMBER, CURRENT_FLAG);

/* Fact indexes */

CREATE INDEX IDX_FACT_RES_PASSENGER ON FACT_RESERVATION(PASSENGER_KEY);
CREATE INDEX IDX_FACT_RES_FLIGHT ON FACT_RESERVATION(FLIGHT_KEY);
CREATE BITMAP INDEX IDX_FACT_RES_CHANNEL ON FACT_RESERVATION(CHANNEL_KEY);
CREATE BITMAP INDEX IDX_FACT_RES_FARE ON FACT_RESERVATION(FARE_CLASS_KEY);

CREATE INDEX IDX_FACT_TICKET_PASSENGER ON FACT_TICKET_REVENUE(PASSENGER_KEY);
CREATE INDEX IDX_FACT_TICKET_FLIGHT ON FACT_TICKET_REVENUE(FLIGHT_KEY);

CREATE INDEX IDX_FACT_PROFIT_FLIGHT ON FACT_FLIGHT_PROFITABILITY(FLIGHT_KEY);
CREATE INDEX IDX_FACT_PROFIT_ROUTE ON FACT_FLIGHT_PROFITABILITY(ROUTE_KEY);

CREATE INDEX IDX_FACT_LOYALTY_PASSENGER ON FACT_LOYALTY_MILES(PASSENGER_KEY);
CREATE INDEX IDX_FACT_PROMO_PASSENGER ON FACT_PROMOTION_RESPONSE(PASSENGER_KEY);
CREATE INDEX IDX_FACT_INTERACTION_PASSENGER ON FACT_CUSTOMER_INTERACTION(PASSENGER_KEY);

/* ============================================================
   8. DATE DIMENSION POPULATION
   Can be run directly in Oracle.
   ============================================================ */

INSERT INTO DIM_DATE (
    DATE_KEY,
    FULL_DATE,
    DAY_NUMBER,
    DAY_NAME,
    MONTH_NUMBER,
    MONTH_NAME,
    QUARTER_NUMBER,
    YEAR_NUMBER,
    WEEK_NUMBER,
    IS_WEEKEND
)
SELECT 
    TO_NUMBER(TO_CHAR(DATE '2020-01-01' + LEVEL - 1, 'YYYYMMDD')) AS DATE_KEY,
    DATE '2020-01-01' + LEVEL - 1 AS FULL_DATE,
    TO_NUMBER(TO_CHAR(DATE '2020-01-01' + LEVEL - 1, 'DD')) AS DAY_NUMBER,
    TRIM(TO_CHAR(DATE '2020-01-01' + LEVEL - 1, 'DAY')) AS DAY_NAME,
    TO_NUMBER(TO_CHAR(DATE '2020-01-01' + LEVEL - 1, 'MM')) AS MONTH_NUMBER,
    TRIM(TO_CHAR(DATE '2020-01-01' + LEVEL - 1, 'MONTH')) AS MONTH_NAME,
    TO_NUMBER(TO_CHAR(DATE '2020-01-01' + LEVEL - 1, 'Q')) AS QUARTER_NUMBER,
    TO_NUMBER(TO_CHAR(DATE '2020-01-01' + LEVEL - 1, 'YYYY')) AS YEAR_NUMBER,
    TO_NUMBER(TO_CHAR(DATE '2020-01-01' + LEVEL - 1, 'IW')) AS WEEK_NUMBER,
    CASE 
        WHEN TO_CHAR(DATE '2020-01-01' + LEVEL - 1, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') IN ('FRI','SAT') 
        THEN 'Y'
        ELSE 'N'
    END AS IS_WEEKEND
FROM dual
CONNECT BY LEVEL <= DATE '2035-12-31' - DATE '2020-01-01' + 1;

COMMIT;